name: build
on:
  pull_request:
    branches:
      - main
    paths:
      - src/mova/**
      - .github/workflows/build-ci.yml
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/mova
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run nx lint
      - run: npm run nx test
      - run: npm run nx build --prod
