name: Build
on:
  pull_request:
    branches:
      - main
      - features/*
    paths:
      - src/mova/**
      - .github/workflows/build-ci.yml
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/mova
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run nx build --prod

      - name: Lint
        run: npm run nx lint

      - name: Test
        run: npm run nx test
