name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/*
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/mova
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.4.1"
          cache: npm

      - name: Print Node.js version
        run: node -v

      - name: Print npm version
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --prod

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
