name: Publish to GitHub Pages
on:
  # TODO: remove pull_request
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - src/mova
      - .gihub/workflows/gihub-pages-cd.yml
jobs:
  github-pages-cd:
    name: Build and Publish to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/mova
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: pwd
      - run: npm install
      - run: npm run nx -- build --prod --output-path dist
      - run: ls -la
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: src/mova/dist
